2020-01-07 00:53:59,179 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:74]
2020-01-07 00:54:03,691 ERROR: Exception on / [GET] [in /home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/home/aman/Projects/Flask/microblog/app/main/routes.py", line 16, in before_request
    if current_user.is_authenticated:
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/werkzeug/local.py", line 307, in _get_current_object
    return self.__local()
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 359, in _load_user
    return self.reload_user()
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 321, in reload_user
    user = self.user_callback(user_id)
  File "/home/aman/Projects/Flask/microblog/app/models.py", line 83, in load_user
    return User.query.get(int(id))
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 982, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 1094, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 284, in load_on_pk_identity
    return q.one()
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3325, in one
    ret = self.one_or_none()
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3294, in one_or_none
    ret = list(self)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/home/aman/Projects/Flask/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen 
FROM user 
WHERE user.id = ?]
[parameters: (1,)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2020-01-07 00:55:32,205 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:74]
2020-01-07 00:56:07,356 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:74]
2020-01-07 00:56:24,582 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:74]
2020-01-07 00:56:56,973 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:74]
2020-01-07 01:04:26,775 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:74]
2020-01-07 01:05:41,676 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:74]
2020-01-07 01:05:57,075 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:74]
2020-01-07 01:09:02,356 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:74]
2020-01-07 01:10:42,792 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:74]
2020-01-08 21:29:06,225 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:74]
2020-01-15 11:36:36,245 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:75]
2020-01-15 11:39:41,674 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:75]
2020-01-15 11:42:32,909 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:75]
2020-01-15 11:46:28,358 INFO: Microblog startup [in /home/aman/Projects/Flask/microblog/app/__init__.py:75]
